### ISSUE TITLE
Autocompletion and syntax highlighting in Intellij IDEA

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/Morganey#246] opened 2016-10-05 18:32 UTC
In order for me to implement auto-completion and syntax highlighting i require a JFlex grammar file for Morganey as detailed [here](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/implementing_lexer.html). I see you already have a BNF definition for Morganey in README, so i tried to use [this](http://bnfc.digitalgrammars.com/) tool with these command line options `--java --jflex` to generate a JFlex grammar from it, However it fails with a lexer error when I Input the BNF. Having a JFlex grammar will allow me to continue implementing autocomplete and syntax highlighting .

Many Thanks

**Comment by rexim** [comment] 2016-10-08 05:21
> However it fails with a lexer error when I Input the BNF

Could you please attach the log of the tool including the error message?

**Comment by 06needhamt** [comment] 2016-10-08 10:09
This is the only output i get

```
C:\Users\thoma\Desktop>bnfc --java --jflex test.bnf > bnfc.log
bnfc: user error (syntax error at line 1 due to lexer error)
```

**Comment by rexim** [comment] 2016-10-08 10:32
@06needhamt please attach the `bnfc.log` and `test.bnf` files.

**Comment by 06needhamt** [comment] 2016-10-08 10:46
I had to put txt on them so GitHub
[bnfc.log.txt](https://github.com/morganey-lang/Morganey/files/517612/bnfc.log.txt)
[test.bnf.txt](https://github.com/morganey-lang/Morganey/files/517613/test.bnf.txt)

 would let me upload

**Comment by ForNeVeR** [comment] 2016-10-08 10:47
@06needhamt better use [Gist](https://gist.github.com/) next time!

**Comment by 06needhamt** [comment] 2016-10-08 10:48
@ForNeVeR ah i forgot about gists i will make one now

**Comment by 06needhamt** [comment] 2016-10-08 10:49
@rexim See https://gist.github.com/06needhamt/7e1fa550d39958c689ca9092bf281573

**Comment by ForNeVeR** [comment] 2016-10-08 10:50
@06needhamt and your `bnfc.log` looks suspicious — as if you taken your command line input and not the log file itself.

_(I'm still downloading bnfc to verify)_

**Comment by 06needhamt** [comment] 2016-10-08 10:51
@ForNeVeR that's all the log is the routed command line output

**Comment by ForNeVeR** [comment] 2016-10-08 11:31
In my case `bnfc.log` is empty. `bnfc: user error (syntax error at line 1 due to lexer error)` is really the only output.

**Comment by rexim** [comment] 2016-10-08 12:10
First of all, the BNF in the README is not a correct BNF. It was created just for the user's information. The first step is gonna be making the BNF in the README a correct BNF specification of the language syntax.

**Comment by rexim** [comment] 2016-10-08 12:11
The issue has been split.

### Pieces
- [x] #248 Make BNF in the README correct so it can be successfully converted by bnfc utility
- [x] #251 Flex grammar for Morganey syntax

**Comment by rexim** [comment] 2016-10-16 21:34
Changed the title of the ticket, because it looked like it's a duplicate of #251

**Comment by 06needhamt** [comment] 2016-10-17 17:28
Also see https://github.com/morganey-lang/morganey-intellij-plugin/issues/4

**Comment by rexim** [comment] 2016-11-19 15:05
According to https://github.com/morganey-lang/morganey-intellij-plugin/issues/17 and https://github.com/morganey-lang/morganey-intellij-plugin/pull/18 this issue is no longer in the scope of this repository. Closing as invalid.

**Closed as completed by rexim** 2016-11-19 15:05 UTC
Labels: invalid, split
